runtime: php55
api_version: 1
threadsafe: true
handlers:

  - url: /assets
    static_dir: assets

  - url: /
    script: index.php

  - url: /(.+)
    script: index.php

beta_settings:
  cloud_sql_instances: ppdb-smk5palembang:us-central1:ppdb-smk5-palembang

runtime_config:
  document_root: .
  # [START enabling_stackdriver_integration]
  enable_stackdriver_integration: true
  # [END enabling_stackdriver_integration]
