runtime: php55
api_version: 1
threadsafe: true

handlers:
  - url: /
    script: index.php
  - url: /(.+)
    script: index.php
  - url: /assets
    static_dir: assets

beta_settings:
  cloud_sql_instances: ppdb-smk5palembang:us-central1:ppdb-smk5-palembang