runtime: php55
api_version: 1
threadsafe: false
handlers:
  - url: /
    script: index.php
  - url: /(.+)
    script: index.php

  - url: /ntunnel_mysql.php
    static_files: ntunnel_mysql.php
    upload: ntunnel_mysql.php